### ISSUE TITLE
use katzenpost v0.0.43

### ISSUE THREAD

**Issue by xendarboh** [0KnowledgeNetwork/opt#53]
#### Related
- #43 
- https://github.com/katzenpost/katzenpost/pull/766
- [Comparing v0.0.38...v0.0.43 · katzenpost/katzenpost](https://github.com/katzenpost/katzenpost/compare/v0.0.38...v0.0.43)

#### TODO
- [ ] if concurrency test works then proceed to merge it:  #44 
- [x] sync (upgrade) related aspects to new katzenpost:
  - [x] `genconfig/`
  - [x] `pki/`
  - [x] `docker/Makefile`, confirm local testnet works with:
    - [x] `pki=voting` (default, ci-tested)
    - [x] `pki=appchain` (manual, developing)
